export const REQUEST_PENDING="REQUEST_PENDING"
export const PRODUCT_REQUEST_SUCCESS="PRODUCT_REQUEST_SUCCESS"
export const REQUEST_FAILURE="REQUEST_FAILURE"
export const REVIEWS_REQUEST_SUCCESS="REVIEWS_REQUEST_SUCCESS"
