export const SIGNIN_REQUEST_ADMIN = "SIGNIN_REQUEST_ADMIN";
export const SIGNIN_SUCCESS_ADMIN = "SIGNIN_SUCCESS_ADMIN";
export const SIGNIN_FAILURE_ADMIN = "SIGNIN_FAILURE_ADMIN";


export const GOTOHOME = "GOTOHOME";
export const LOGOUT = "LOGOUT";
export const SETID = "SETID";